name: Run on .config or kernel-url Change

on:
  push:
    paths:
      - ".config"
      - "kernel-url"

jobs:
  process-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log Change
        run: |
          echo "The .config or kernel-url file has been modified. Processing changes..."
         
      - name: Install wget and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar
          git config user.name "Linus Torvalds"  # Cool-sounding username
          git config user.email "linus@kernel.org"  # Fictional email for Linus Torvalds

      - name: download and push kernel
        run: |
          wget -i kernel-url -O kernel.tar.xz
          tar -xf kernel.tar.xz
          git add ./kernel
          git commit -m "push kernel"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
