name: Run on .config Change

on:
  push:
    paths:
      - ".config"
      - "kernel-url" 

jobs:
  process-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log Change
        run: |
          echo "The .config file has been modified. Processing changes..."
         
      - name: Install wget
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -i kernel-url
          
