name: Run on .config or kernel-url Change

on:
  push:
    paths:
      - ".config"
      - "kernel-url"

jobs:
  process-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log Change
        run: |
          echo "The .config or kernel-url file has been modified. Processing changes..."
         
      - name: Install wget and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar
          git config user.name "Linus Torvalds"  # Cool-sounding username
          git config user.email "linus@kernel.org"  # Fictional email for Linus Torvalds

      - name: download and push kernel
        run: |
          wget -i kernel-url -O kernel.tar.xz
          mkdir -p kext
          tar -xvf kernel.tar.xz -C kext
          cd kext
          make -j$(nproc)

      - name: Upload kernel
        uses: actions/upload-artifact@v3
        with:
          name: kernel.efi
          path: kext/arch/x86/boot/bzImage   
          

