name: Run on .config or kernel-url Change

on:
  push:
    paths:
      - ".config"
      - "kernel-url"

jobs:
  process-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log Change
        run: |
          echo "The .config or kernel-url file has been modified. Processing changes..."
         
      - name: Install wget and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar

      - name: Download and Extract Kernel Tarball
        run: |
          KERNEL_URL=$(cat kernel-url)
          wget -N "$KERNEL_URL"
          FILE_NAME=$(basename "$KERNEL_URL")
          tar -xf "$FILE_NAME"
        
      - name: Get Extracted Folder Name
        id: get-folder-name
        run: |
          EXTRACTED_FOLDER=$(basename "$FILE_NAME" .tar.xz)
          echo "extracted_folder=$EXTRACTED_FOLDER" >> $GITHUB_ENV

      - name: Configure Git User
        run: |
          git config user.name "Linus Torvalds"  # Cool-sounding username
          git config user.email "linus@kernel.org"  # Fictional email for Linus Torvalds

      - name: Add and Commit Extracted Kernel Folder
        run: |
          git add ${{ env.extracted_folder }}
          git commit -m "Add extracted kernel folder: ${{ env.extracted_folder }}"

      - name: Push Extracted Kernel Folder
        run: |
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
