name: Run on .config or kernel-url Change

on:
  push:
    paths:
      - "runner"
 

jobs:
  process-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log Change
        run: |
          echo "The .config or kernel-url file has been modified. Processing changes..."
         
      - name: Install wget and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar libncurses-dev bison flex libssl-dev libelf-dev bc zstd

      - name: download and push kernel
        run: |
          wget -q -i kernel-url -O kernel.tar.xz
          mkdir -p kext
          tar -xf kernel.tar.xz -C kext --strip-components=1
          cp .config kext/
          cd kext
          wget https://github.com/kzwkt/inspiron-351-fw/archive/refs/heads/main.zip
          unzip main.zip
          make -j$(nproc)

      - name: Upload kernel
        uses: actions/upload-artifact@v3
        with:
          name: kernel.efi
          path: kext/arch/x86/boot/bzImage   
          

