name: Run on .config or kernel-url Change

on:
  push:
    paths:
      - "runner"

jobs:
  process-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: install deps Download, extract, and build kernel
        run: |
          bash build.sh

      - name: Set dynamic tag version
        run: |
          VERSION="v$(date +'%Y%m%d%H%M%S')"  # Format: vYYYYMMDDHHMMSS
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create a new GitHub release and tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "This release includes the latest build stable kernel."
          files: |
            kext/arch/x86/boot/bzImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
